<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProcessTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('process')->delete();
        
        \DB::table('process')->insert(array (
            0 => 
            array (
                'id' => 1,
                'order_id' => 3,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 6,
                'quantity' => 1471,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-03-30 15:10:03',
                'updated_at' => '2024-03-30 15:10:03',
                'daleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'order_id' => 4,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 6,
                'quantity' => 1,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-03-30 15:10:03',
                'updated_at' => '2024-03-30 15:10:03',
                'daleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'order_id' => 6,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 6,
                'quantity' => 121,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-03-30 15:10:03',
                'updated_at' => '2024-03-30 15:10:03',
                'daleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'order_id' => 7,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 6,
                'quantity' => 212,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-03-30 15:10:03',
                'updated_at' => '2024-03-30 15:10:03',
                'daleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'order_id' => 8,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 6,
                'quantity' => 188,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-03-30 15:10:03',
                'updated_at' => '2024-03-30 15:10:03',
                'daleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'order_id' => 9,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 6,
                'quantity' => 164,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-03-30 15:10:03',
                'updated_at' => '2024-03-30 15:10:03',
                'daleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'order_id' => 10,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 6,
                'quantity' => 14,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-03-30 15:10:03',
                'updated_at' => '2024-03-30 15:10:03',
                'daleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'order_id' => 11,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 6,
                'quantity' => 1,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-03-30 15:10:03',
                'updated_at' => '2024-03-30 15:10:03',
                'daleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'order_id' => 12,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 6,
                'quantity' => 453,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-03-30 15:10:03',
                'updated_at' => '2024-03-30 15:10:03',
                'daleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'order_id' => 14,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 6,
                'quantity' => 208,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-03-30 15:10:03',
                'updated_at' => '2024-03-30 15:10:03',
                'daleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'order_id' => 16,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 6,
                'quantity' => 276,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-03-30 15:10:03',
                'updated_at' => '2024-03-30 15:10:03',
                'daleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'order_id' => 17,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 6,
                'quantity' => 383,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-03-30 15:10:03',
                'updated_at' => '2024-03-30 15:10:03',
                'daleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'order_id' => 18,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 6,
                'quantity' => 530,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-03-30 15:10:03',
                'updated_at' => '2024-03-30 15:10:03',
                'daleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'order_id' => 19,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 6,
                'quantity' => 898,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-03-30 15:10:03',
                'updated_at' => '2024-03-30 15:10:03',
                'daleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'order_id' => 20,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 6,
                'quantity' => 1081,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-03-30 15:10:03',
                'updated_at' => '2024-03-30 15:10:03',
                'daleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'order_id' => 21,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 6,
                'quantity' => 1280,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-03-30 15:10:03',
                'updated_at' => '2024-03-30 15:10:03',
                'daleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'order_id' => 3,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 18,
                'quantity' => 740,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 12:56:09',
                'updated_at' => '2024-04-02 16:47:15',
                'daleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'order_id' => 6,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 18,
                'quantity' => 19,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 12:56:09',
                'updated_at' => '2024-04-02 14:04:26',
                'daleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'order_id' => 7,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 18,
                'quantity' => 108,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 12:56:09',
                'updated_at' => '2024-04-02 15:52:29',
                'daleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'order_id' => 8,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 18,
                'quantity' => 141,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 12:56:09',
                'updated_at' => '2024-04-02 14:04:26',
                'daleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'order_id' => 9,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 18,
                'quantity' => 99,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 12:56:09',
                'updated_at' => '2024-04-02 15:37:08',
                'daleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'order_id' => 10,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 18,
                'quantity' => 13,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 12:56:09',
                'updated_at' => '2024-04-02 14:04:26',
                'daleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'order_id' => 11,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 18,
                'quantity' => 1,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 12:56:09',
                'updated_at' => '2024-04-02 13:59:59',
                'daleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'order_id' => 12,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 18,
                'quantity' => 282,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 12:56:09',
                'updated_at' => '2024-04-02 17:11:51',
                'daleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'order_id' => 14,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 18,
                'quantity' => 166,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 12:56:09',
                'updated_at' => '2024-04-02 15:37:08',
                'daleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'order_id' => 16,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 18,
                'quantity' => 158,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 12:56:09',
                'updated_at' => '2024-04-02 17:11:51',
                'daleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'order_id' => 17,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 18,
                'quantity' => 242,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 12:56:09',
                'updated_at' => '2024-04-02 16:09:04',
                'daleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'order_id' => 18,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 18,
                'quantity' => 451,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 12:56:10',
                'updated_at' => '2024-04-02 16:41:26',
                'daleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'order_id' => 19,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 18,
                'quantity' => 580,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 12:56:10',
                'updated_at' => '2024-04-02 16:54:28',
                'daleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'order_id' => 20,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 18,
                'quantity' => 733,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 12:56:10',
                'updated_at' => '2024-04-02 17:11:51',
                'daleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'order_id' => 21,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 18,
                'quantity' => 899,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 12:56:10',
                'updated_at' => '2024-04-02 16:54:28',
                'daleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'order_id' => 3,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 14,
                'quantity' => 431,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:41:34',
                'updated_at' => '2024-04-02 16:47:15',
                'daleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'order_id' => 6,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 14,
                'quantity' => 13,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:41:34',
                'updated_at' => '2024-04-02 15:41:34',
                'daleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'order_id' => 7,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 14,
                'quantity' => 51,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:41:34',
                'updated_at' => '2024-04-02 15:52:29',
                'daleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'order_id' => 8,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 14,
                'quantity' => 10,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:41:34',
                'updated_at' => '2024-04-02 15:41:34',
                'daleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'order_id' => 9,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 14,
                'quantity' => 84,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:41:34',
                'updated_at' => '2024-04-02 15:41:34',
                'daleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'order_id' => 10,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 14,
                'quantity' => 2,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:41:34',
                'updated_at' => '2024-04-02 15:41:34',
                'daleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'order_id' => 12,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 14,
                'quantity' => 4,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:41:34',
                'updated_at' => '2024-04-02 15:41:34',
                'daleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'order_id' => 14,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 14,
                'quantity' => 145,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:41:34',
                'updated_at' => '2024-04-02 15:41:34',
                'daleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'order_id' => 16,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 14,
                'quantity' => 99,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:41:34',
                'updated_at' => '2024-04-02 15:41:34',
                'daleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'order_id' => 17,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 14,
                'quantity' => 118,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:41:34',
                'updated_at' => '2024-04-02 16:09:05',
                'daleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'order_id' => 18,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 14,
                'quantity' => 269,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:41:34',
                'updated_at' => '2024-04-02 15:41:34',
                'daleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'order_id' => 19,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 14,
                'quantity' => 200,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:41:34',
                'updated_at' => '2024-04-02 16:54:29',
                'daleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'order_id' => 20,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 14,
                'quantity' => 416,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:41:34',
                'updated_at' => '2024-04-02 17:11:52',
                'daleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'order_id' => 21,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 14,
                'quantity' => 520,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:41:34',
                'updated_at' => '2024-04-02 16:54:29',
                'daleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'order_id' => 3,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 15,
                'quantity' => 282,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:43:20',
                'updated_at' => '2024-04-02 16:01:53',
                'daleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'order_id' => 6,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 15,
                'quantity' => 6,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:43:20',
                'updated_at' => '2024-04-02 15:43:20',
                'daleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'order_id' => 7,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 15,
                'quantity' => 2,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:43:20',
                'updated_at' => '2024-04-02 15:43:20',
                'daleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'order_id' => 8,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 15,
                'quantity' => 125,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:43:20',
                'updated_at' => '2024-04-02 15:43:20',
                'daleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'order_id' => 9,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 15,
                'quantity' => 10,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:43:20',
                'updated_at' => '2024-04-02 15:43:20',
                'daleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'order_id' => 10,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 15,
                'quantity' => 9,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:43:20',
                'updated_at' => '2024-04-02 15:43:20',
                'daleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'order_id' => 11,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 15,
                'quantity' => 1,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:43:20',
                'updated_at' => '2024-04-02 15:43:20',
                'daleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'order_id' => 12,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 15,
                'quantity' => 120,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:43:20',
                'updated_at' => '2024-04-02 15:43:20',
                'daleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'order_id' => 14,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 15,
                'quantity' => 22,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:43:20',
                'updated_at' => '2024-04-02 15:43:20',
                'daleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'order_id' => 16,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 15,
                'quantity' => 53,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:43:20',
                'updated_at' => '2024-04-02 17:11:52',
                'daleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'order_id' => 17,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 15,
                'quantity' => 119,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:43:20',
                'updated_at' => '2024-04-02 15:43:20',
                'daleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'order_id' => 18,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 15,
                'quantity' => 172,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:43:20',
                'updated_at' => '2024-04-02 15:43:20',
                'daleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'order_id' => 19,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 15,
                'quantity' => 305,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:43:20',
                'updated_at' => '2024-04-02 15:43:20',
                'daleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'order_id' => 20,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 15,
                'quantity' => 308,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:43:20',
                'updated_at' => '2024-04-02 15:43:20',
                'daleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'order_id' => 21,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 15,
                'quantity' => 301,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:43:20',
                'updated_at' => '2024-04-02 15:43:20',
                'daleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'order_id' => 3,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 16,
                'quantity' => 30,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:44:28',
                'updated_at' => '2024-04-02 15:44:28',
                'daleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'order_id' => 7,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 16,
                'quantity' => 55,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:44:28',
                'updated_at' => '2024-04-02 15:44:28',
                'daleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'order_id' => 8,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 16,
                'quantity' => 7,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:44:28',
                'updated_at' => '2024-04-02 15:44:28',
                'daleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'order_id' => 9,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 16,
                'quantity' => 5,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:44:28',
                'updated_at' => '2024-04-02 15:44:28',
                'daleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'order_id' => 10,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 16,
                'quantity' => 2,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:44:28',
                'updated_at' => '2024-04-02 15:44:28',
                'daleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'order_id' => 12,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 16,
                'quantity' => 158,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:44:28',
                'updated_at' => '2024-04-02 17:11:52',
                'daleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'order_id' => 16,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 16,
                'quantity' => 6,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:44:28',
                'updated_at' => '2024-04-02 15:44:28',
                'daleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'order_id' => 17,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 16,
                'quantity' => 5,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:44:28',
                'updated_at' => '2024-04-02 15:44:28',
                'daleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'order_id' => 18,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 16,
                'quantity' => 10,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:44:28',
                'updated_at' => '2024-04-02 16:41:26',
                'daleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'order_id' => 19,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 16,
                'quantity' => 75,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:44:28',
                'updated_at' => '2024-04-02 15:44:28',
                'daleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'order_id' => 20,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 16,
                'quantity' => 14,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:44:28',
                'updated_at' => '2024-04-02 15:44:28',
                'daleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'order_id' => 21,
                'old_variation_id' => NULL,
                'new_variation_id' => NULL,
                'given_by_id' => NULL,
                'taken_by_id' => NULL,
                'process_type_id' => 16,
                'quantity' => 80,
                'description' => NULL,
                'linked_id' => NULL,
                'status' => 1,
                'created_at' => '2024-04-02 15:44:28',
                'updated_at' => '2024-04-02 15:44:28',
                'daleted_at' => NULL,
            ),
        ));
        
        
    }
}