<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'category' => 1,
                'brand' => 1,
            'model' => 'Apple AirPods 2nd gen (2019) Lightning Charging case',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:04',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'category' => 1,
                'brand' => 1,
            'model' => 'Apple AirPods Pro 1st gen (2019) Wireless Charging case',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:04',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'category' => 3,
                'brand' => 1,
            'model' => 'Apple Watch (Series 4) 2018 GPS + Cellular 44',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:04',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'category' => 3,
                'brand' => 1,
            'model' => 'Apple Watch (Series 4) 2018 GPS 40',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:04',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'category' => 3,
                'brand' => 1,
            'model' => 'Apple Watch (Series 4) 2018 GPS 44',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:04',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'category' => 3,
                'brand' => 1,
            'model' => 'Apple Watch (Series 5) 2019 GPS 40',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:04',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'category' => 3,
                'brand' => 1,
            'model' => 'Apple Watch (Series 5) GPS 44',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:04',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'category' => 3,
                'brand' => 1,
            'model' => 'Apple Watch (Series 6) 2020 GPS 40',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:04',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'category' => 3,
                'brand' => 1,
            'model' => 'Apple Watch (Series 6) 2020 GPS 44',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:04',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'category' => 3,
                'brand' => 1,
            'model' => 'Apple Watch (Series 7) 2021 GPS 41',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:04',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'category' => 3,
                'brand' => 1,
            'model' => 'Apple Watch (Series 7) 2021 GPS 45',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:04',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'category' => 3,
                'brand' => 1,
            'model' => 'Apple Watch (Series 8) 2022 GPS 41',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:04',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'category' => 3,
                'brand' => 1,
            'model' => 'Apple Watch (Series 8) 2022 GPS 45',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'category' => 3,
                'brand' => 1,
            'model' => 'Apple Watch (Series SE) 2020 GPS + Cellular 40',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'category' => 3,
                'brand' => 1,
            'model' => 'Apple Watch (Series SE) 2020 GPS 40',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'category' => 3,
                'brand' => 1,
            'model' => 'Apple Watch (Series SE) 2020 GPS 44',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'category' => 3,
                'brand' => 1,
            'model' => 'Apple Watch (Ultra) 2022 GPS + Cellular 49',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'category' => 3,
                'brand' => 1,
            'model' => 'Apple Watch (Ultra) 2022 GPS 49',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'category' => 1,
                'brand' => 1,
                'model' => 'EarPods with Lightning Connector',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'category' => 7,
                'brand' => 1,
            'model' => 'Mac mini (November 2020) M1 3',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'category' => 4,
                'brand' => 11,
                'model' => 'Meta Quest Pro VR headset',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'category' => 8,
                'brand' => 2,
            'model' => 'Samsung Galaxy Book Go 14-inch (2021) Snapdragon 7c 4GB SSD 128 GB QWERTY English',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'category' => 1,
                'brand' => 2,
                'model' => 'Samsung Galaxy buds Bluetooth Earphones Black',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'category' => 1,
                'brand' => 2,
                'model' => 'Samsung Galaxy Buds2 Pro Earbud Noise-Cancelling Bluetooth Earphones',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'category' => 3,
                'brand' => 2,
                'model' => 'Samsung Smart Watch Galaxy Watch 46mm HR GPS',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'category' => 3,
                'brand' => 2,
                'model' => 'Samsung Smart Watch Gear S HR GPS',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'category' => 3,
                'brand' => 2,
                'model' => 'Samsung Smart Watch Gear S3 Frontier HR GPS',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 13 Pro',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 13 Pro Max',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 14 Pro',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 14 Pro Max',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 15 Pro',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 15 Pro Max',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'category' => 5,
                'brand' => 7,
                'model' => 'Xbox One S',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'category' => 9,
                'brand' => 6,
                'model' => 'Caterpillar Cat S62',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy A22',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy A22 5G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy A23',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy A42 5G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy A42 5G Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy A51',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy A51 Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy A52s 5G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy A70 Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'category' => 9,
                'brand' => 2,
            'model' => 'Galaxy A9 (2018) Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy A90 5G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy Note20 Ultra 5G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy Note9',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:05',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy Note9 Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S10',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S10 Plus',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S10 Plus Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S10e',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S20',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S20 5G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S20 5G Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S20 FE',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S20 Plus',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S20 Plus 5G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S20 Plus Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S20 Ultra 5G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S21',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => '2024-03-28 13:01:11',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S21 Plus',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => '2024-03-28 13:01:13',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S21 Ultra',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => '2024-03-28 13:01:15',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S22',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => '2024-03-28 12:18:11',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S22 Plus Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => '2024-03-28 12:18:35',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S22 Ultra',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => '2024-03-28 12:18:22',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S23',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S23 Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S9 Plus',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy Z Flip 3',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => '2024-03-28 12:58:55',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy Z Flip 4',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => '2024-03-28 12:59:03',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'category' => 9,
                'brand' => 3,
                'model' => 'Google Pixel',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'category' => 9,
                'brand' => 3,
                'model' => 'Google Pixel 4',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'category' => 9,
                'brand' => 3,
                'model' => 'Google Pixel 4 XL',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'category' => 9,
                'brand' => 3,
                'model' => 'Google Pixel 5',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'category' => 9,
                'brand' => 3,
                'model' => 'Google Pixel 6',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'category' => 9,
                'brand' => 3,
                'model' => 'Google Pixel 6 Pro',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'category' => 9,
                'brand' => 3,
                'model' => 'Google Pixel 6A',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'category' => 9,
                'brand' => 3,
                'model' => 'Google Pixel 7',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'category' => 9,
                'brand' => 3,
                'model' => 'Google Pixel 7 Pro',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'category' => 9,
                'brand' => 9,
                'model' => 'Huawei Mate 10 Pro',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'category' => 9,
                'brand' => 9,
                'model' => 'Huawei P30 Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'category' => 6,
                'brand' => 1,
            'model' => 'iPad 10.2 (2019) 7th gen WiFi',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'category' => 6,
                'brand' => 1,
            'model' => 'iPad 10.2 (2019) 7th gen WiFi + 4G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'category' => 6,
                'brand' => 1,
            'model' => 'iPad 10.2 (2020) 8th gen WiFi',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'category' => 6,
                'brand' => 1,
            'model' => 'iPad Pro 12.9 (2021) 5th gen WiFi',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'category' => 6,
                'brand' => 1,
            'model' => 'iPad Pro 12.9 (2021) 5th gen WiFi + 5G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 11',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 12',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 12 mini',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 12 Pro',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 12 Pro Max',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 13',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 13 mini',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 14',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:08',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 14 Dual eSIM',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:08',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 14 Plus',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:08',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 14 Pro Dual eSIM',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:08',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 14 Pro Max Dual eSIM',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:08',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 15',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:08',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 15 Plus',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:08',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 7',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:08',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 7 Plus',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:08',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 8',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:08',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'category' => 9,
                'brand' => 1,
            'model' => 'iPhone SE (2020)',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:08',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'category' => 9,
                'brand' => 1,
            'model' => 'iPhone SE (2022)',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:08',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone XR',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:08',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'category' => 8,
                'brand' => 1,
            'model' => 'MacBook Air Retina 13.3-inch (2018) Core i5 8GB SSD 128 QWERTY English',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:08',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'category' => 9,
                'brand' => 5,
                'model' => 'OnePlus 10 Pro',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:08',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'category' => 9,
                'brand' => 5,
                'model' => 'OnePlus 10T Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:08',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'category' => 9,
                'brand' => 5,
                'model' => 'OnePlus 7T Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:08',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'category' => 9,
                'brand' => 5,
                'model' => 'OnePlus Nord N20',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'category' => 9,
                'brand' => 4,
                'model' => 'Xiaomi 12X Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'category' => 9,
                'brand' => 4,
                'model' => 'Xiaomi Mi 9 Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy A5',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'category' => 9,
                'brand' => 2,
            'model' => 'Galaxy A5 (2016)',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'category' => 9,
                'brand' => 2,
            'model' => 'Galaxy J3 (2017)',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy J4 Plus Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy J5',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy J7 Pro',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            121 => 
            array (
                'id' => 122,
                'category' => 6,
                'brand' => 2,
                'model' => 'Galaxy Tab A WiFi + 4G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            122 => 
            array (
                'id' => 123,
                'category' => 6,
                'brand' => 1,
            'model' => 'iPad 4 (2012) HDD 16 GB (WiFi)',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            123 => 
            array (
                'id' => 124,
                'category' => 6,
                'brand' => 1,
            'model' => 'iPad Air (2013) WiFi',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            124 => 
            array (
                'id' => 125,
                'category' => 6,
                'brand' => 1,
            'model' => 'iPad Air (2014) 2nd gen 16 Go WiFi',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            125 => 
            array (
                'id' => 126,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 5S 16 GB',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            126 => 
            array (
                'id' => 127,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 6 16 GB',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            127 => 
            array (
                'id' => 128,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 6S',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            128 => 
            array (
                'id' => 129,
                'category' => 9,
                'brand' => 10,
                'model' => 'Motorola Moto G4',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            129 => 
            array (
                'id' => 130,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy Note10',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            130 => 
            array (
                'id' => 131,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy Note10 Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            131 => 
            array (
                'id' => 132,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy Note10 Plus',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            132 => 
            array (
                'id' => 133,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy Note10 Plus 5G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            133 => 
            array (
                'id' => 134,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy Note20',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            134 => 
            array (
                'id' => 135,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy Note20 5G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            135 => 
            array (
                'id' => 136,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy Note20 5G Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            136 => 
            array (
                'id' => 137,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy Note20 Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            137 => 
            array (
                'id' => 138,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy Note20 Ultra',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            138 => 
            array (
                'id' => 139,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S10 5G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            139 => 
            array (
                'id' => 140,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S21 Ultra 5G Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:09',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            140 => 
            array (
                'id' => 141,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S22 Plus',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:10',
                'updated_at' => '2024-03-28 12:23:24',
                'deleted_at' => NULL,
            ),
            141 => 
            array (
                'id' => 142,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S23 Plus',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:10',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            142 => 
            array (
                'id' => 143,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S23 Plus Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:10',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            143 => 
            array (
                'id' => 144,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S23 Ultra',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:10',
                'updated_at' => '2024-04-07 10:31:07',
                'deleted_at' => NULL,
            ),
            144 => 
            array (
                'id' => 145,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy Z Flip 5',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:10',
                'updated_at' => '2024-03-28 12:59:06',
                'deleted_at' => NULL,
            ),
            145 => 
            array (
                'id' => 146,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy Z Fold 2 5G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:10',
                'updated_at' => '2024-03-28 12:59:09',
                'deleted_at' => NULL,
            ),
            146 => 
            array (
                'id' => 147,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy Z Fold 3 5G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:10',
                'updated_at' => '2024-03-28 12:59:11',
                'deleted_at' => NULL,
            ),
            147 => 
            array (
                'id' => 148,
                'category' => 6,
                'brand' => 1,
            'model' => 'iPad Air (2020) 4th gen WiFi',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:10',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            148 => 
            array (
                'id' => 149,
                'category' => 6,
                'brand' => 1,
            'model' => 'iPad Air (2022) 5th gen WiFi',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:10',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            149 => 
            array (
                'id' => 150,
                'category' => 6,
                'brand' => 1,
            'model' => 'iPad Pro 10.5 (2017) 1st gen WiFi + 4G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:10',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            150 => 
            array (
                'id' => 151,
                'category' => 6,
                'brand' => 1,
            'model' => 'iPad Pro 12.9 (2020) 4th gen WiFi',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:10',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            151 => 
            array (
                'id' => 152,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 11 Pro',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:11',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            152 => 
            array (
                'id' => 153,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 11 Pro Max',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:11',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            153 => 
            array (
                'id' => 154,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 14 Plus Dual eSIM',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:12',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            154 => 
            array (
                'id' => 155,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 8 Plus',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:12',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            155 => 
            array (
                'id' => 156,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone X',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:12',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            156 => 
            array (
                'id' => 157,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone XS',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:12',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            157 => 
            array (
                'id' => 158,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone XS Max',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:12',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            158 => 
            array (
                'id' => 159,
                'category' => 7,
                'brand' => 1,
            'model' => 'Mac mini (January 2023) M2 3.49 GHz SSD 256 GB 8GB',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:12',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            159 => 
            array (
                'id' => 160,
                'category' => 8,
                'brand' => 1,
            'model' => 'MacBook Air 13.3-inch (2020) Apple M1 8-core and 7-core GPU 8GB RAM SSD QWERTY English',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:12',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            160 => 
            array (
                'id' => 161,
                'category' => 8,
                'brand' => 1,
            'model' => 'MacBook Air Retina 13.3-inch (2018) Core i5 8GB SSD 256 QWERTY English',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            161 => 
            array (
                'id' => 162,
                'category' => 8,
                'brand' => 1,
            'model' => 'MacBook Pro 13.3-inch (2020) Apple M1 8-core and 8-core GPU 8GB RAM SSD QWERTY English',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            162 => 
            array (
                'id' => 163,
                'category' => 8,
                'brand' => 7,
            'model' => 'Microsoft Surface Laptop 13-inch (2017) Core i5-7300U 8GB SSD 256 GB AZERTY French',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            163 => 
            array (
                'id' => 164,
                'category' => 8,
                'brand' => 7,
                'model' => 'Microsoft Surface Pro 5 12-inch Core i5-7300U SSD 256 GB 8GB',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            164 => 
            array (
                'id' => 165,
                'category' => 2,
                'brand' => 1,
            'model' => 'Apple TV HD (2015) SSD',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            165 => 
            array (
                'id' => 166,
                'category' => 2,
                'brand' => 1,
            'model' => 'Apple TV HD (2021) SSD',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            166 => 
            array (
                'id' => 167,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy A10 Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            167 => 
            array (
                'id' => 168,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy A10s Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            168 => 
            array (
                'id' => 169,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy A12',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            169 => 
            array (
                'id' => 170,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy A20',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            170 => 
            array (
                'id' => 171,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy A21s',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            171 => 
            array (
                'id' => 172,
                'category' => 9,
                'brand' => 2,
            'model' => 'Galaxy A5 (2017)',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            172 => 
            array (
                'id' => 173,
                'category' => 9,
                'brand' => 2,
            'model' => 'Galaxy A6 (2018)',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            173 => 
            array (
                'id' => 174,
                'category' => 9,
                'brand' => 2,
            'model' => 'Galaxy A6 Plus (2018)',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            174 => 
            array (
                'id' => 175,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy J6 Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            175 => 
            array (
                'id' => 176,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy J6 Plus',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            176 => 
            array (
                'id' => 177,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S6',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            177 => 
            array (
                'id' => 178,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S6 edge',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            178 => 
            array (
                'id' => 179,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S7 edge',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            179 => 
            array (
                'id' => 180,
                'category' => 6,
                'brand' => 2,
            'model' => 'Galaxy Tab A (2019) WiFi',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            180 => 
            array (
                'id' => 181,
                'category' => 6,
                'brand' => 2,
                'model' => 'Galaxy Tab A 10.1 WiFi + 4G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            181 => 
            array (
                'id' => 182,
                'category' => 6,
                'brand' => 2,
                'model' => 'Galaxy Tab A6 WiFi + 4G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            182 => 
            array (
                'id' => 183,
                'category' => 6,
                'brand' => 2,
                'model' => 'Galaxy Tab A7 WiFi + 4G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            183 => 
            array (
                'id' => 184,
                'category' => 6,
                'brand' => 2,
                'model' => 'Galaxy Tab S3 WiFi + 4G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            184 => 
            array (
                'id' => 185,
                'category' => 6,
                'brand' => 2,
                'model' => 'Galaxy Tab WiFi',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            185 => 
            array (
                'id' => 186,
                'category' => 9,
                'brand' => 9,
                'model' => 'Huawei P9',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            186 => 
            array (
                'id' => 187,
                'category' => 6,
                'brand' => 1,
            'model' => 'iPad 9.7 (2017) 5th gen WiFi',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            187 => 
            array (
                'id' => 188,
                'category' => 6,
                'brand' => 1,
            'model' => 'iPad 9.7 (2018) 6th gen WiFi',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            188 => 
            array (
                'id' => 189,
                'category' => 6,
                'brand' => 1,
            'model' => 'iPad 9.7 (2018) 6th gen WiFi + 4G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            189 => 
            array (
                'id' => 190,
                'category' => 6,
                'brand' => 1,
            'model' => 'iPad Pro 9.7 (2016) 1st gen WiFi',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            190 => 
            array (
                'id' => 191,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 6 32 GB',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            191 => 
            array (
                'id' => 192,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 6S Plus',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            192 => 
            array (
                'id' => 193,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone SE',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            193 => 
            array (
                'id' => 194,
                'category' => 9,
                'brand' => 8,
                'model' => 'Sony Xperia X',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            194 => 
            array (
                'id' => 195,
                'category' => 9,
                'brand' => 8,
                'model' => 'Sony Xperia Z5',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            195 => 
            array (
                'id' => 196,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy Fold',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:13',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            196 => 
            array (
                'id' => 197,
                'category' => 9,
                'brand' => 1,
                'model' => 'iPhone 15 Pro Max Dual eSIM',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:14',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            197 => 
            array (
                'id' => 198,
                'category' => 8,
                'brand' => 1,
            'model' => 'MacBook Air 13.3-inch (2020) Apple M1 8-core and 7-core GPU 16GB RAM SSD QWERTY English',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:14',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            198 => 
            array (
                'id' => 199,
                'category' => 8,
                'brand' => 1,
            'model' => 'MacBook Air 13.3-inch (2020) Apple M1 8-core and 8-core GPU 16GB RAM SSD QWERTY English',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:14',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            199 => 
            array (
                'id' => 200,
                'category' => 8,
                'brand' => 1,
            'model' => 'MacBook Air 13.3-inch (2020) Apple M1 8-core and 8-core GPU 8GB RAM SSD QWERTY English',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:15',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            200 => 
            array (
                'id' => 201,
                'category' => 8,
                'brand' => 1,
            'model' => 'MacBook Pro 13.3-inch (2020) Apple M1 8-core and 8-core GPU 16GB RAM SSD QWERTY English',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:15',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            201 => 
            array (
                'id' => 202,
                'category' => 2,
                'brand' => 1,
            'model' => 'Apple TV 4K (2017) SSD',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:15',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            202 => 
            array (
                'id' => 203,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy A30',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:15',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            203 => 
            array (
                'id' => 204,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy A31',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:15',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            204 => 
            array (
                'id' => 205,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy A32',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:15',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            205 => 
            array (
                'id' => 206,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy A32 5G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:15',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            206 => 
            array (
                'id' => 207,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy A40 Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:15',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            207 => 
            array (
                'id' => 208,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy A50',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:15',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            208 => 
            array (
                'id' => 209,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy Note8',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:15',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            209 => 
            array (
                'id' => 210,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S8',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:15',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            210 => 
            array (
                'id' => 211,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S8 Plus',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:15',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            211 => 
            array (
                'id' => 212,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S9',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:15',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            212 => 
            array (
                'id' => 213,
                'category' => 6,
                'brand' => 2,
                'model' => 'Galaxy Tab A7 WiFi',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:15',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            213 => 
            array (
                'id' => 214,
                'category' => 6,
                'brand' => 2,
                'model' => 'Galaxy Tab A8 WiFi + 4G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:15',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            214 => 
            array (
                'id' => 215,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy Xcover 5',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:16',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            215 => 
            array (
                'id' => 216,
                'category' => 9,
                'brand' => 3,
                'model' => 'Google Pixel 3',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:16',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            216 => 
            array (
                'id' => 217,
                'category' => 9,
                'brand' => 3,
                'model' => 'Google Pixel 3 XL',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:16',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            217 => 
            array (
                'id' => 218,
                'category' => 9,
                'brand' => 3,
                'model' => 'Google Pixel 3a',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:16',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            218 => 
            array (
                'id' => 219,
                'category' => 9,
                'brand' => 3,
                'model' => 'Google Pixel 3a XL',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:16',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            219 => 
            array (
                'id' => 220,
                'category' => 9,
                'brand' => 9,
                'model' => 'Huawei P Smart Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:16',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            220 => 
            array (
                'id' => 221,
                'category' => 6,
                'brand' => 1,
            'model' => 'iPad 10.2 (2021) 9th gen WiFi',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:16',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            221 => 
            array (
                'id' => 222,
                'category' => 6,
                'brand' => 1,
            'model' => 'iPad Air (2014) 2nd gen WiFi',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:16',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            222 => 
            array (
                'id' => 223,
                'category' => 6,
                'brand' => 1,
            'model' => 'iPad Air (2020) 4th gen WiFi + 4G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:16',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            223 => 
            array (
                'id' => 224,
                'category' => 6,
                'brand' => 1,
            'model' => 'iPad Pro 11 (2018) 1st gen WiFi',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:16',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            224 => 
            array (
                'id' => 225,
                'category' => 6,
                'brand' => 1,
            'model' => 'iPad Pro 12.9 (2018) 3rd gen WiFi',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:16',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            225 => 
            array (
                'id' => 226,
                'category' => 9,
                'brand' => 4,
                'model' => 'Xiaomi Redmi Note 11 Dual Sim',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:17',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            226 => 
            array (
                'id' => 227,
                'category' => 5,
                'brand' => 8,
                'model' => 'PlayStation 5 5G',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:17',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            227 => 
            array (
                'id' => 228,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S24',
                'description' => NULL,
                'created_at' => '2024-03-28 12:00:06',
                'updated_at' => '2024-03-28 13:01:11',
                'deleted_at' => NULL,
            ),
            228 => 
            array (
                'id' => 229,
                'category' => 9,
                'brand' => 2,
                'model' => 'Galaxy S23 Ultra Dual Sim',
                'description' => NULL,
                'created_at' => '2024-04-15 10:20:11',
                'updated_at' => '2024-04-15 10:20:11',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}